---
abstract: "Clone of PHP's date and time functions."
author:
  - 'Aran Deltac <bluefeet@gmail.com>'
build_requires:
  Test::Simple: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PHP-DateTime
requires:
  Time::DaysInMonth: 99.1117
  Time::HiRes: 1.9721
  Time::Local: 1.2000
  Time::Timezone: 2006.0814
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=PHP-DateTime
  repository: git://github.com/bluefeet/PHP-DateTime.git
version: 0.06
